{{- define "chrt-6456.password" -}}
{{- randAlphaNum 128 | nospace -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: rocketadmin-postgresql-secret
  labels:
    {{- include "rocketadmin.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{.Values.auth.password}}
  postgres-password: {{ include "rocketadmin.dbPassword" . }}
