{{- define "app-domain-address" -}}
  {{- if .Values.hostname }}
    {{- .Values.hostname -}}
  {{- else if (and .Values.ingress.enabled .Values.ingress.hosts) -}}
    {{- (.Values.ingress.hosts | first).host -}}
  {{- else -}}
    ''
  {{- end -}}
{{- end -}}
{{- define "gen.secret" -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace "rocketadmin" -}}
{{- if $secret -}}
{{/*
   Reusing value of secret if exist
*/}}
JWT_SECRET: {{ $secret.data.JWT_SECRET | b64dec | quote }}
PRIVATE_KEY: {{ $secret.data.PRIVATE_KEY | b64dec | quote }}
{{- else -}}
JWT_SECRET: {{ randAlphaNum 64 | quote }}
PRIVATE_KEY: {{ randAlphaNum 64 | quote }}
{{- end -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rocketadmin.fullname" . }}
  labels:
    {{- include "rocketadmin.labels" . | nindent 4 }}
type: Opaque
stringData:
{{ ( include "gen.secret" . ) | indent 2}}
  APP_DOMAIN_ADDRESS: {{ include "app-domain-address" . }}
{{- if .Values.postgresql.enabled}}
  DATABASE_URL: postgresql://rocketadmin:{{urlquery .Values.auth.password}}@{{ include "rocketadmin.postgresql.fullname" . }}/rocketadmin
{{- end -}}
{{- if .Values.pglite.enabled }}
  PGLITE_FOLDER: /var/lib/rocketadmin
{{- end}}
{{- if .Values.email.enabled }}
  EMAIL_CONFIG_STRING: "smtp://{{urlquery .Values.email.username}}:{{urlquery .Values.email.password}}@{{.Values.email.host}}:{{.Values.email.port}}"
  EMAIL_FROM: {{.Values.email.from}}
  OPENAI_API_KEY: {{.Values.config.openai_api_key}}
{{- end }}
