{{- define "chrt-6456.password" -}}
{{- randAlphaNum 24 | nospace -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: rocketadmin
  namespace: default
type: Opaque
data:
  JWT_SECRET: {{ include "chrt-6456.password" .}}
  PRIVATE_KEY: {{ include "chrt-6456.password" .}}
