{{- define "chrt-6456.password" -}}
{{- randAlphaNum 128 | nospace -}}
{{- end -}}
{{- define "app-domain-address" -}}
  {{- if .Values.hostname }}
    {{- .Values.hostname -}}
  {{- else if (and .Values.ingress.enabled .Values.ingress.hosts) -}}
    {{- (.Values.ingress.hosts | first).host -}}
  {{- else -}}
    ''
  {{- end -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rocketadmin.fullname" . }}
  labels:
    {{- include "rocketadmin.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ include "chrt-6456.password" .}}
  PRIVATE_KEY: {{ include "chrt-6456.password" .}}
  APP_DOMAIN_ADDRESS: {{ include "app-domain-address" . }}
  DATABASE_URL: postgresql://rocketadmin:{{urlquery .Values.auth.password}}@{{ include "rocketadmin.postgresql.fullname" . }}/rocketadmin
{{- if .Values.email.enabled }}
  EMAIL_CONFIG_STRING: "smtp://{{urlquery .Values.email.username}}:{{urlquery .Values.email.password}}@{{.Values.email.host}}:{{.Values.email.port}}"
  EMAIL_FROM: {{.Values.email.from}}
{{- end }}
