{{- define "chrt-6456.password" -}}
{{- randAlphaNum 128 | nospace -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rocketadmin.fullname" . }}
  labels:
    {{- include "rocketadmin.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ include "chrt-6456.password" .}}
  PRIVATE_KEY: {{ include "chrt-6456.password" .}}
  DATABASE_URL: postgresql://rocketadmin:{{ include "rocketadmin.dbPassword" . }}@{{ include "rocketadmin.postgresql.fullname" . }}/rocketadmin
