{{- define "chrt-6456.password" -}}
{{- randAlphaNum 128 | nospace -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rocketadmin.fullname" . }}
  labels:
    {{- include "rocketadmin.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ include "chrt-6456.password" .}}
  PRIVATE_KEY: {{ include "chrt-6456.password" .}}
  DATABASE_URL: postgresql://rocketadmin:{{.Values.auth.password}}@{{ include "rocketadmin.postgresql.fullname" . }}/rocketadmin
{{- if .Values.email.enabled }}
  EMAIL_CONFIG_STRING: "smtp://{{.Values.email.username}}:{{.Values.email.password}}@{{.Values.email.host}}:{{.Values.email.port}}"
{{- end }}
